
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install  modules
      run: yarn
    
    - name: Run app tests
      run: cd app && yarn --coverage
    
    - name: Build Next app
      run: cd app && yarn build

    - name: Run api tests
      run: cd api && yarn test --coverage

    - name: Build API 
      run: cd api && yarn build
