
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install  modules
      run: yarn
    
    - name: Run app tests
      run: cd app && yarn test --coverage

    - name: Run api tests
      run: cd api && yarn test --coverage

    - name: Merge results
      run: yarn mergeCoverage

    - name: coveralls
      uses: coverallsapp/github-action@master
      with:
        flag-name: test-api
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./lcov.info

